language: ruby
rvm:
- 2.1
gemfile: jekyll/Gemfile
before_script:
- "./simonlee.sh copy"
- cd jekyll
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --only-4xx --disable-external --empty-alt-ignore
deploy:
  provider: s3
  access_key_id:
    secure: Npv27iQors9pKn2HJUWHcc6p2s5TjmbKkywLeU/jb2yCrmnntHue+zVvDICRarEbpMBh9MS0m4grASpEJ4OlEP5qV5Mkve/n7uXwWvnk0hapZS+nVD72FwKY0rUb6LfP4rsqedkcrU1VKnbSxezx+dneHp54RMGKl7+OKTmt4PzSAYjpbOdPw5oj7xea1tgBCaZCKunz9P3+f4/Ql7/VA2YN+K15RGM/70H4XTwu+zO1egByNVo6C/R8Y1SBqxd6NfB9FjQYtuSid8CSM2O6J5WssTJJ1fYVG8uDhYugDZmCYb5VoMzEijPG77svhye1ICtahGN5c9vRYZ/ofUifXjyA2aW5mGF5m3SYEzSb8nZIUPLJ33ZabtEMSuqrVV0YoGVUwsV4NuJQVRiM/iDrD+hNKi4WfM2lICPgUSSCPFId2GFX4FN8DHhKrfnJKlXb5kfskt4kvL27PT51YKeyfSwxmX14OfSs5gLrlW0GmGa35QbtFNLrRguJI9mjjLV3peWr5C2xbXVJ4AtsgHf1WHmA6XVxsQfxhNJVvNr2BupK9hqdyU0yZuYwo7AQMFlY/B4gC81EKmQcoNehynw2pbP17pd/OccZTLXW+XrXORZyY+rideCWLG9i16CfQmjZjkc3ykt+BVYKAMgc3LYHAyaEx0Xm/9IxPqVjId009JE=
  secret_access_key:
    secure: FJOFo4YFMmdTpDKIORBx4Na45N1tq69LTpq9JneJ95frR5aJSBhGBSiFxou20L7/QEiHTYbvqZTRsg4VRspG2q9+P/zsXyxlwgGFP9sr4UV9R8cbPXZodbXvJ60NTLE0lOLK/7NBZCIZ5fPOFtXGXmGPIBiW8/SUYUKxdUVa0NJKAUpwufkyWvDjmOIpC/DTmUx62HHOwxcdC/vbKEQVEB86TBH4ohaiHChyfCVADccf3ugO9TJeR+3pNMa3ZnEqk/NUtWeUgZc3x+qI2aq2lklqD9HDQShJq31R/khhRyCmx8K2fyRm6KNi9C8wtxcmzjz6XZ9Ha7OBnYRn3itvnY3dtisUhP4efcac067Ap0CmyBrQ2GAUtFJkjegFdkuUZk8ZpFOoHviviGnnkWddp4cvaWxzwRp9jc/MKXoFGg5PHzPVrYwZRAB0BKuA4OkH6pLf9EuSEE0cy7aDdtIOpIaQA3uQb+W0VrXwbu5vIDUlngHyLGJnYO2dT/G6TtYuimKpbsD6zJ7+We4Qg2lZdcQxV+qcs8rtwreqUNNYCnEX/2U2jv56gxbB5orQX/d5bBEk7LoWEIv1VZkxcZ+8h3cy4IaPUKe6ydk3SpF32dHf4uQQ9k0HmKlMKGiPYj7xBeg7PBmKEH1zUa92FlZ77rzweyoZAwYyCuuGxCgaoaU=
  bucket: simonlee.me
  skip_cleanup: true
  region: eu-west-1
  local_dir: "$TRAVIS_BUILD_DIR/jekyll/_site"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production
