
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://simonlee.me"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id to track your visitors

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Simon Lee"
title: "Simon E. Lee"
description: "Blog and website of Simon Lee. Opinions expressed are mine."
keywords: "lee, simon, personal"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Love the confusion."
  - text: "Where’s your will to be weird?"
  - text: "Look for the little miracles unfolding right now."

me-img: "/img/author.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 10

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "simonleeme"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/arup.png"
    date: "September 2014 - Today"
    description: "Doing Mechanical Engineering at [Arup](http://www.arup.com)"

  - image: "/img/timeline/imperial.jpg"
    date: "October 2010 - July 2014"
    description: "Studied Mechanical Engineering at [Imperial College London](http://www.imperial.ac.uk/mechanical-engineering)"

  - image: "/img/timeline/nomura.png"
    date: "Jul 2013 - Sep 2013"
    description: "Equity Research Analyst at [Nomura](http://www.nomura.com/)"

  - image: "/img/timeline/ssp.png"
    date: "Aug 2012 - Sep 2012"
    description: "Engineering consulting at [Sepakat Setia Perunding](http://www.sspsb.com.my/)"

  - image: "/img/timeline/imperial.jpg"
    date: "Aug 2012 - Sep 2012"
    description: "Student Researcher at [Imperial College London](http://www.imperial.ac.uk/mechanical-engineering)"


# First image of the Timeline

timeline-img: "/img/timeline/birth.jpg"

###########
# Contact #
###########

email: "simon@simonlee.me"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Simon Lee is a nice person. He lives in London, where he works on three-dimensional engineering projects. In his spare time, Simon likes to eat pizza."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/hellosimonlee"
  - title: "github"
    url: "https://github.com/bestbananapie"
  - title: "linkedin"
    url: "https://linkedin.com/in/leesimoneric"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  CV: 'resume'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
